version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
     - "6380:6379"
    # volumes:
    #   - $PWD/redis-data:/var/lib/redis
    #   - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
  api_salud:
    image: stanlee321/api_salud:latest
    ports:
      - "8002:8000"
    env_file:
      - ../../config/api_salud.env
    image: stanlee321/fastapi-front:latest
    ports:
      - "3000:80"
    links:
      - fastapi
volumes:
  minio_volume:
  postgres_volume: